version: "3"

networks:
  bot:
    external: false

services:
  backend:
    image: {{username}}/bot:{{version}}
    restart: always
    networks:
      - bot
    environment:
      - TZ=UTC
    volumes:
      - {{mount_folder}}/db:/app/db
      - {{mount_folder}}/bot_token.txt:/app/bot_token.txt